feat: add npaw event listener
bcc-code/bccm-player pull request #75
Opened 2024-10-31 16:14 UTC by sifferhans

## About the changes
This PR introduces an NPAW event listener that makes it possible to hook into NPAWs video events.
This makes it possible to introspect and/or extract whatever data we want before it is sent to NPAW.

2024-11-04 13:17 UTC, andreasgangso requested changes

2024-11-04 13:17 UTC, andreasgangso commented on pigeons/playback_platform_pigeon.dart
> +  late Map<String?, String?>? data;
There more I think about it, the more i think its probably a better idea to pass the unique id in the mediaitem.
Or if you want to keep this approach, i would have the data more typed:
```
late String playerId;
late AnalyticsEventType type; // an enum

```

2024-11-06 12:52 UTC, sifferhans commented
@KillerX  Seems like the `onMediaItemTransition` runs four times in quick succession when playing a video. This results in 4 events in Rudderstack for each play event.
Is this going to be a problem?

@andreasgangso Is there a way to prevent the 4x events?

2024-11-07 10:00 UTC, KillerX approved these changes

2024-11-07 10:28 UTC, merged